version: 2.1
apiVersion: v1alpha
kind: espresso
sauce:
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - junit
      - espresso
      - accessibility
    build: Release $CI_COMMIT_SHORT_SHA
espresso:
  app: ./app/build/outputs/apk/debug/app-debug.apk
  testApp: ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
suites:
  - name: "Deque Android AxeDevTools Sample App"
    testOptions:
      clearPackageData: false
      useTestOrchestrator: false
    emulators:
      - name: "Android GoogleAPI Emulator"
        platformVersions:
          - "14.0"
    devices:
      - name: "Google.*"
        platformVersion: "14"